name: ZonePracticeLite
version: '1.0'
main: dev.nandi0813.practice.Practice
authors: [ Nandi0813 ]
depend: [ ProtocolLib ]
commands:
  arena:
  ladder:
  setup:
  practice:
    aliases: [prac, zonepractice, zoneprac, zonep]
  staff:
  spectate:
    aliases: spec
  party:
    aliases: p
  matchinv:

permissions:
  zonepractice.admin:
    children:
      zonepractice.setup: true
      zonepractice.practice: true
      zonepractice.staff: true
  zonepractice.setup:
    description: Setup everything.
  zonepractice.practice:
    description: Practice permission.
  zonepractice.staff:
    description: Staff permission.

  # Basic permission
  zonepractice.spectate:
    default: true

  # Party permissions
  zonepractice.party.create:
    description: Create party.

  # Bypasses
  zonepractice.bypass.ranked.requirements:
    description: Bypass ranked requirements.

  # Custom Kits
  zonepractice.customkit:
    description: Create custom kit for ladders.