name: ZonePracticeLite
version: '2.2'
main: dev.nandi0813.practice.Practice
authors: [ Nandi0813 ]
depend: [ ProtocolLib ]
commands:
  arena:
  ladder:
  practice:
    aliases: [prac, zonepractice, zoneprac, zonep]
  spectate:
    aliases: spec
  party:
    aliases: p
  matchinv:
  statistics:
    aliases: [stats]
  leaderboard:

permissions:
  zonepractice.admin:
    children:
      zonepractice.setup: true
      zonepractice.practice: true
      zonepractice.staff: true
  zonepractice.setup:
    description: Setup everything, like arenas, ladders..
  zonepractice.practice:
    description: Practice permission.
  zonepractice.match.forceend:
    description: Ends any matches instantly.
  zonepractice.staff:
    description: Staff permission.
  zonepractice.stats.resetall:
    description: Resets all player stats.
  zonepractice.reload:
    description: Reload the config & language files.

  # Basic permission
  zonepractice.spectate:
    default: true
  zonepractice.spectate.silent:
    description: The server doesn't send message to the match player, when the player with the permission starts spectating.
  zonepractice.stats:
    description: View other players statistics.

  # Party permissions
  zonepractice.party.create:
    description: Create party.

  # Bypasses
  zonepractice.bypass.ranked.requirements:
    description: Bypass ranked requirements.
  zonepractice.bypass.match.forceend:
    description: Bypasses the match end command.

  # Custom Kits
  zonepractice.customkit:
    description: Create custom kit for ladders.